image: Ubuntu  # образ для сборки

stack: jdk 11

branches:
  only:
    - main

build: off

steps:
  - name: Grant execute permission for gradlew
    run: chmod +x gradlew

install:
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info

